### ISSUE TITLE
Add endpoint for working with tags

### ISSUE THREAD

**Issue by czottmann** [czottmann/obsidian-actions-uri#10]
See discussion #9, started by @FelipeRearden.

Research how to get the current list of tags, and create an endpoint which'll return it.

**Comment by FelipeRearden** [comment]
> Research how to get the current list of tags, and create an endpoint which'll return it.

Based on this post on Templater repository, I think the current list of tags is `Object.keys(app.metadataCache.getTags()`

→ Maybe this information could save some time 🔎

Source [here](https://github.com/SilentVoid13/Templater/discussions/756#discussioncomment-3527601)
