### ISSUE TITLE
Preferred routes for deprecated routes reference self

### ISSUE THREAD

**Issue by nickynicolson** [czottmann/obsidian-actions-uri#19]
See e.g. 
[/open/daily-note](https://czottmann.github.io/obsidian-actions-uri/routes/open/#opendaily-note-deprecated-since-v012)
[/open/note](https://czottmann.github.io/obsidian-actions-uri/routes/open/#opennote-deprecated-since-v012)

Should respectively point to:
- `/daily-note/open-current`
- `/note/open`

**Comment by czottmann** [comment]
@nickynicolson  Good find, thank you! I'll fix it later today!

**Comment by czottmann** [comment]
Corrected!
