### ISSUE TITLE
[ZCO-160] [Feature Request] Search Outside Obsidian

### ISSUE THREAD

**Issue by FelipeRearden** [czottmann/obsidian-actions-uri#36]
Hello @czottmann !!!!!!!

I would like to share with you an idea about how we could search for content from Obsidian using the Shortcuts App.

The FR is simple to explain: a way to search for content from a specific vault based on a user input that is generated from the Shortcuts App.

Let me explain why I need this feature ...

## My Workflow

I use Obsidian 90% of the time from iPad with mouse and keyboard.
- I cant use Alfred or Raycast :(
- I rely on the Shortcuts App as my automation tool,

In a nutshell, I have content that I need to search from 4 sources:
- Web Articles in Goodlinks App
- Web Articles from Reeder 5 App
- Text from DEVONthink to Go App
- Text from Obsidian

For the 3 first sources, I have built a shortcut that searches for content from these three sources based on a `Ask for Input Action`.

It generates a list from content from these sources and open the content that I choose from the list in the App that the content is saved.

## My FR

My FR is about adding content from Obsidian to this list and cover 100% of my content.

ℹ️ Basically what I am asking is an external output from the content that the **Core Plugin** `Search All Files` presents inside Obsidian.

## Simple Example

Imagine that I have these notes inside my vault:

1️⃣ `NBA.md` with the content **Lorem Ipsum**

2️⃣ `Michael Jordan.md` with the content **Lorem Ipsum**

3️⃣ `Chicago Bulls.md` with the content **Michael Jordan**

I expect this behavior when I type **Michael Jordan** using the `Ask for Input` action 
- Search for Filenames with **Michael Jordan**
- Search for **Michael Jordan** inside the content of the notes 

This way the result from this action would be a URI to open the Note in Obsidian. 
- I would just use the action `Open URL` to execute the URI generated from the new Action.

I this example, it would bring the notes `Michael Jordan.md` and `Chicago Bulls.md`

---

Thanks for reading this !!!!! I hope you like my idea 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

<sub>[ZCO-160](https://linear.app/actionsdotwork/issue/ZCO-160/[feature-request]-search-outside-obsidian)</sub>

**Comment by czottmann** [comment]
Thanks for the feature request! I think you can already achieve what you want with the existing endpoints, most importantly [`/search/all-notes`](https://czottmann.github.io/obsidian-actions-uri/routes/search/#searchall-notes). The search query is passed as-is into Obsidian.

Here's a screenshot of a Shortcuts workflow:

<img width="619" alt="CleanShot 2023-01-25 at 15 28 46@2x" src="https://user-images.githubusercontent.com/1501/214589778-848a4c50-0da8-486e-888c-44239171f33e.png">

(The "Pretty Print" action is c/o https://sindresorhus.com/actions.)

Is this what you're looking for, or am I missing something?

**Comment by FelipeRearden** [comment]
> Is this what you're looking for, or am I missing something?

Thank you very much for your reply @czottmann !!!!!! THIS EXACTLY WHAT I AM LOOKING FOR 💙💙💙

Unfortunately I could not finish the shortcut. I get **stuck** at the the action in red. I waited for 10 minutes to see you it could finish. 

I replicate your shortcut. Take a look 👀 

Search for `czottmann` that exists in a note `InfoNotes.DraftNote.md` and in `czottmann.md`

![73C8F013-8925-4304-87A0-758573120D6F](https://user-images.githubusercontent.com/85180696/214604229-568716cc-92ba-4faa-9597-a307efbac34d.jpeg)

💻 My Environment

iPadOS 16.2
Obsidian 1.4.1 (last public release)
Actions URI 0.15.0 

Do you have any idea why I cant run on iPadOS (since you are on MacOS) ?

I know that Obsidian Mobile version that is equal to the Desktop version is in private beta yet. Might be the reason ?

---

Thank you very much for your help :)
 I hope we could get this work, my feeling is that we are so close :)

**Comment by FelipeRearden** [comment]
@czottmann 

I tried to investigate by using the plugin [Obsidian Mobile Logging](https://github.com/shabegom/obsidian-mobile-logging) and this is the information that I got from the console on Mobile

```
[log] Received callback URL obsidian://actions-uri/search/all-notes?vault=Mobile&query=czottmann&x-cancel=shortcuts-production://x-callback-url/ic-cancel/1508F79A-0958-4D08-9BCB-BD3EDEF80632&x-error=shortcuts-production://x-callback-url/ic-error/1508F79A-0958-4D08-9BCB-BD3EDEF80632&x-source=Shortcuts&x-success=shortcuts-production://x-callback-url/ic-success/1508F79A-0958-4D08-9BCB-BD3EDEF80632 
[log] Received URL action [object Object]
```

This time I am at another vault 

![B0A69F83-362D-4130-9F52-D3DB5A9D7B56](https://user-images.githubusercontent.com/85180696/214608741-bfef1c56-6e15-42fa-99ee-a2311bd2651f.jpeg)


I hope it helps 🙏

**Comment by czottmann** [comment]
Thanks for the mobile logging output, it's indeed helpful! Alright, so I can see that Actions URI was initialized and has set up the endpoint `/search/all-notes`. I can also see that it doesn't cause any errors. 

But I see that the search list itself doesn't open, and that's what Actions URI uses to gather the search results. It's possible that the search code I wrote doesn't work (anymore?) on mobile. 😐 

I'll need to investigate this, so I'll convert this issue into a discussion and create a new ticket with a bug report, which I'll link from here, then.
