### ISSUE TITLE
Research Dataview support 

### ISSUE THREAD

**Issue by czottmann** [czottmann/obsidian-actions-uri#4]
Based on the idea in #3: I need to research whether or not it's doable and feasible to add Dataview support. It'd be nice if there was a route that accepts DQL queries and returns Dataview results.

**Comment by SimplGy** [comment]
(flyby) there are docs on integrating with dataview as a plugin developer [here](https://blacksmithgu.github.io/obsidian-dataview/plugin/develop-against-dataview/)

**Comment by czottmann** [comment]
Initial DV support for `TABLE` and `LIST` queries is in, will be included in the upcoming v0.14.

I'll add a follow-up ticket for `TASK` queries.
