### ISSUE TITLE
My commands do not work since the last update

### ISSUE THREAD

**Issue by Ornicar85** [czottmann/obsidian-actions-uri#81]
Hello,

First, thanks for you great work, your plugin removes a lot of frictions in my day to day tasks.

Since the last update, the two commands I have set up do not work anymore, could you please help me understand why ? 
Here are they :

obsidian://actions-uri/daily-note/create?vault=MY%20SECOND%20BRAIN%20V3&if-exists=skip

obsidian://actions-uri/weekly-note/create?vault=MY%20SECOND%20BRAIN%20V3&if-exists=skip

Please take in consideration that nothing has changed in my environment except this update.
The Periodic note plugin is still enabled, and my vault still named the same.

Kind regards,

-Jules

**Comment by czottmann** [comment]
Hi @Ornicar85, it still works fine for me, and I haven't really touched anything in the last update. Could you please copy/paste the debug info from Obsidian here? Command palette → Show debug info.

**Comment by Ornicar85** [comment]
Hello Carlo,

Thank you very much for your prompt reply and for your time.

Here is the debug info:

SYSTEM INFO:
      Obsidian version: v1.4.16
      Installer version: v1.4.13
      Operating system: Windows 10 Home 10.0.22621
      Login status: logged in
      Catalyst license: none
      Insider build toggle: off
      Live preview: on
      Legacy editor: off
      Base theme: light
      Community theme: Minimal v7.3.3
      Snippets enabled: 0
      Restricted mode: off
      Plugins installed: 22
      Plugins enabled: 21
            1: Dataview v0.5.64
            2: QuickAdd v1.6.0
            3: Metadata Menu v0.6.4
            4: Text Generator v0.5.14-beta
            5: Whisper v1.5.1
            6: Templater v1.18.1
            7: Smart Connections v1.6.37
            8: Plugin Update Tracker v1.5.2
            9: Commander v0.5.1
            10: Calendar v1.5.10
            11: Note Refactor v1.8.2
            12: Workspaces Plus v0.3.3
            13: Excalidraw v2.0.4
            14: Link Favicons v1.8.3
            15: Readwise Official v2.0.1
            16: Recent Files v1.3.8
            17: Advanced Tables v0.19.1
            18: Periodic Notes v0.0.17
            19: Todoist Link v2.2.0
            20: Copilot v2.4.4
            21: Actions URI v1.4.0

RECOMMENDATIONS:
      Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
      Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.


Kind regards,

-Jules
________________________________
De : Carlo Zottmann ***@***.***>
Envoyé : jeudi 30 novembre 2023 16:42
À : czottmann/obsidian-actions-uri ***@***.***>
Cc : Ornicar85 ***@***.***>; Mention ***@***.***>
Objet : Re: [czottmann/obsidian-actions-uri] My commands do not work since the last update (Issue #81)


Hi @Ornicar85<https://github.com/Ornicar85>, it still works fine for me, and I haven't really touched anything in the last update. Could you please copy/paste the debug info from Obsidian here? Command palette → Show debug info.

**Comment by czottmann** [comment]
Thanks! Hmm, nothing out of the ordinary there. My current working theory is that there's another plugin intercepting the calls to Actions URI, but that's just a very vague guess. More research is necessary! :)

If you're up for it, please [install my logging helper plugin Logstravaganza](https://obsidian.md/plugins?search=zottmann). (This will pipe Obsidian's logging output into a new note.) Once it's installed:

1. Enable it — this will create a new note `LOGGING NOTE (your device name).md` in your vault root folder.
2. Disable, then re-enable Actions URI.
3. Call the URLs again, the ones that failed.

At this point, the note created by Logstravaganza should contain a table with several rows. At least one of them should contain output by Actions URL. If so, disable Logstravaganza, and send me the note. If you don't want to upload it here, send it via email to carlo@zottmann.org.

**Comment by czottmann** [comment]
@Ornicar85 Attachments are dropped by GitHub when replying by email, I'm afraid. Could you either upload it right here on GH or send it via email to carlo@zottmann.org, please?

**Comment by czottmann** [comment]
Issue was fixed via email, closing.
