### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [czottmann/obsidian-actions-uri#82]
Hi,

I'm wondering if there is any kind of authentication I can put in place?

Do all apps on my android have access to my obsidian notes as long as they now the Vault's name?

Thank you

**Comment by czottmann** [comment]
I doubt any plugin could implement any meaningful authentication. So I'm not sure there is much to be done. If you want this question answered, I'd suggest asking the Obsidian support or maybe check out the official Discord. The links are on the official site, see [Community - Obsidian](https://obsidian.md/community).
