### ISSUE TITLE
command/list silently fails

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [czottmann/obsidian-actions-uri#83]
Hello,

I have two commands. The first one works, the second one doesn't.

Any help would be appreciated!

this one works:
obsidian://actions-uri/note/get?vault=Life&file=home&x-success=http%3A%2F%2Flocalhost%3A8000&x-error=http%3A%2F%2Flocalhost%3A8000

this one does nothing:
obsidian://actions-uri/command/list?vault=Life&x-success=http%3A%2F%2Flocalhost%3A8000&x-error=http%3A%2F%2Flocalhost%3A8000

**Comment by czottmann** [comment]
Hi @SunnyAureliusRichard, thanks for the report. Which version of Actions URI is installed? The `/command/` routes were introduced in 1.3; if you're on 1.3+, then it'd be helpful if you could open Obsidian's web inspector before calling the `obsidian://actions-uri/command/list?` URI – there should be something in the web inspector's console.

**Comment by SunnyAureliusRichard** [comment]
hi @czottmann ,

Thank you for the quick reply.

This is what I see in my console:
![image](https://github.com/czottmann/obsidian-actions-uri/assets/100728856/ee105f73-c997-46bc-abe7-0cbe3c60d232)

In the use case mentioned in the original post the URL is opened in the browser.

**Comment by czottmann** [comment]
Looks like the call is being sent, there's no error, but there'd be one if Obsidian were unable to send it. In my tests, it also works well, plus it's running in production on several hundred Apple devices, meaning it can't be entirely broken.

Are you on Windows, Linux or macOS?

**Comment by SunnyAureliusRichard** [comment]
That's on Windows. Let me try with an empty-ish vault, I'm thinking the payload might be too large.

I'll report back.

**Comment by czottmann** [comment]
It might be possible that the HTTP receiver is cutting off the payload, indeed. On macOS, I've registered custom handlers (`x-callback-test://`, `x-devnull://` etc.) using a 3rd party app, and piped the incoming calls into a text file. I'd be surprised if there isn't something similar for Windows…

**Comment by SunnyAureliusRichard** [comment]
hi again @czottmann,

I've created an empty vault, installed this plugin, ran the commands above and it works as expected.

If there is a way I can share the list of plugins I have and if that would be helpful in fixing this let me know.

Thanks!

**Comment by czottmann** [comment]
I don't think the list of plugins would be helpful. I still suspect the `x-success` URL is too long for Windows to handle. I'm just speculating, but in your case, Obsidian is calling a `http://` URL, which means your default browser is responsible for handling this potentially very long URL, and might cut it off – see [What Is the Maximum Length of a URL in Different Browsers?](https://github.com/czottmann/obsidian-actions-uri/issues/83).

As happy as I am about bug reports (I am!), I doubt this issue is caused by either Obsidian or Actions URI.

**Comment by SunnyAureliusRichard** [comment]
The length of the URL is around 25kb which should be in range for Chrome.

I guess a solution to this issue is to paginate the response - send a few responses each containing up to 100 commands for example.

Please feel free to close this issue, however, as I personally only needed the list of commands once, which I managed to get from the console output. No one else might need this issue fixed and it would be wasted effort.

Thanks for your assistance.

**Comment by czottmann** [comment]
@SunnyAureliusRichard Just for clarification:

> As happy as I am about bug reports (I am!), I doubt this issue is caused by either Obsidian or Actions URI.

This was not a veiled _"please go away"_, mind! 😉 It's just: I believe that using a `http://`` URL as `x-*` parameter _might_ cause this problem, whereas a "real" URI scheme might not. I don't have access to a Windows machine to test that hypothesis, though.

**Comment by SunnyAureliusRichard** [comment]
It is possible, usually I choose to go for a POST request if the payload is big.

Sincerely, no issue on my side, I don't mind if we leave it here.
