### ISSUE TITLE
Make `x-*` parameters optional in `/command/execute` route

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [czottmann/obsidian-actions-uri#84]
Hello,

Can command/execute have optional callback parameters instead of required?

I would like to have this URL:
obsidian://actions-uri/command/execute?vault=Life&commands=bookmarks%3Aopen

over this one, which opens a browser window unnecessirily:
obsidian://actions-uri/command/execute?vault=Life&commands=bookmarks%3Aopen&x-success=http%3A%2F%2Flocalhost%3A8000&x-error=http%3A%2F%2Flocalhost%3A8000

This would be helpful for me on my phone as I can create a URL shortcut that would open obsidian straight to my bookmarks, instead of navigating to bookmarks myself.

Thank you for taking it into consideration.

**Comment by czottmann** [comment]
Good idea, especially since commands never return values. I'll make `x-success` and `x-error` optional in the upcoming version.
