### ISSUE TITLE
"Check for Note" opens the note?

### ISSUE THREAD

**Issue by deanpribetic** [czottmann/obsidian-actions-uri#86]
I am running a Shortcut that employs the "Check for Note" action. I have noticed that running that action also opens the note being checked…is there a way to turn this off?

**Comment by czottmann** [comment]
Hi @deanpribetic, are you talking about the [Actions For Obsidian](https://actions.work/actions-for-obsidian) action? If so: wrong channel, this repo is for the companion plugin only. ;)

That said: I agree it's not desirable. I'll add a toggle to [Check For Existence Of Note](https://support.actions.work/article/23-check-for-existence-of-note) and [Check For Existence Of Periodic Note](https://support.actions.work/article/36-daily-notes-check-for-existence-of-daily-note) in the upcoming version!
