### ISSUE TITLE
[Feature Request] Date to Append/Prepend

### ISSUE THREAD

**Issue by kzssc** [czottmann/obsidian-actions-uri#87]
Hi Carlo, 

It'd be great if the following could be implemented when appending/prepending into a note, e.g. syntax formatted date/time before/after text. 

So: [date/time]: [TEXT] / [TEXT]:[date/time]
e.g. 20240329-1143: [TEXT]

Many thanks!

**Comment by czottmann** [comment]
I try to keep the functionality as generic as possible, and that addition would be way too specific for my taste. For example, you might like it that way, but the next person would like another prefix or a different timestamp format or something.

It's simple enough to add that prefix/suffix to the `content` parameter yourself when calling the URI – so I won't add that feature, sorry.
