### ISSUE TITLE
Might be some problems in the ActionsURI Document

### ISSUE THREAD

**Issue by Moyf** [czottmann/obsidian-actions-uri#88]
In this document page:
https://zottmann.dev/obsidian-actions-uri/routes/file/
![image](https://github.com/czottmann/obsidian-actions-uri/assets/4013062/e63a2370-dcd6-43bb-baa4-11f21d0b1546)

I'm not sure if it's a typo because when using `/vault/get-active` I got nothing return..

And if use `file/get-active` I can get the result, but not like what is said in document:
![image](https://github.com/czottmann/obsidian-actions-uri/assets/4013062/4e44e909-2925-4d9c-8e0b-bc0543c58bcd)

Instead, I still got the relative path to the vault, rather than the fullpath of file:
![image](https://github.com/czottmann/obsidian-actions-uri/assets/4013062/53ee0b14-4b9d-4426-a315-924fd9c73139)

**Comment by czottmann** [comment]
Hi @Moyf, thanks for your ticket.

> I'm not sure if it's a typo because when using /vault/get-active I got nothing return..

Yes, it's a typo, thanks for reporting it! 😅

> And if use file/get-active I can get the result, but not like what is said in document:

Ah, that's a mistake on my end, apologies. `result-filepath` will return the path starting from the vault's root folder.

Both errors are fixed now!

**Comment by Moyf** [comment]
Thank you for fixing it! <3

By the way, I'm not sure if I missed something - is there any API to directly obtain the absolute path of active file in one step? Or do I have to first get the path of the vault through `/vault` , and then combine it with the relative path? 
(This way requires sending two requests, which can be a bit troublesome 🤔)

**Comment by czottmann** [comment]
It's the latter. Obsidian itself does not return absolute paths, so Actions URI doesn't, either. Most of my own work happens on macOS and iOS, and I almost never need the absolute path for anything. ;)

**Comment by Moyf** [comment]
> It's the latter. Obsidian itself does not return absolute paths, so Actions URI doesn't, either. Most of my own work happens on macOS and iOS, and I almost never need the absolute path for anything. ;)

Roger that, thanks!  :D
