### ISSUE TITLE
Inputs to Apple Shortcuts via url-scheme doesn’t play nice with Actions URI’s x-callback-url

### ISSUE THREAD

**Issue by ces3001** [czottmann/obsidian-actions-uri#89]
The problem is Apple Schortcut’s ability to run a shortcut from a URL ignores Action URI’s parameters it is sending in the URL. 
Apple’s URL scheme only reads `input` and `text` url parameters and ignores the rest.

So the below code callback URL
would become `shortcuts://run-shortcut?name=Show_Result&input=text&text=&result-data....`
but the `result-data` parameter is ignored.

Is there any way to encapsulate the appended url string to the x-callback, so that it doesn’t have `&` in it? or set the parameter name to `text` or what other solutions might you propose (other than using Actions for Obsidian ;)

Thanks!
Cecil

```applescript
set query to "LIST
FROM \"Book\"
WHERE status = \"reading\""

set success_url to "shortcuts://run-shortcut?name=Show_Result&input=text&text="
set error_url to "hortcuts://run-shortcut?name=Show_Result&input=text&text=Error"
open location ¬
	"obsidian://actions-uri/dataview/list-query?vault=Cecil&debug-mode=true" & "&dql=" & Cecil's encodeTextURL(query) ¬
	& "&x-success=" & Cecil's encodeTextURL(success_url) ¬
	& "&x-error=" & Cecil's encodeTextURL(error_url)
```

**Comment by czottmann** [comment]
Hi! I'm afraid the output parameters of Actions URI are "fixed", i.e. there's no way to bundle them up as a JSON string or anything so they'd be usable as the value of the `text` parameter that `shortcuts://` is accepting.

Frankly, I don't see a way to make Actions URI happening with `shortcuts://` – the latter is **extremely** basic when it comes to accepting inputs.

If you're willing to tinker, I can recommend the free [LinCastor 2.4](https://macdownload.informer.com/lincastor/) (_not_ LinCastor Browser!) which lets you register custom URL schemes on your Mac which can be tied to scripts, so calls to these URIs trigger those scripts. I've been using it for years by now for various tasks, I like it a lot, even though it's a bit fiddly.

If you're willing to spend money, then yes, Actions For Obsidian _obviously_ is a solid choice ;) but also Keyboard Maestro which also offers an URL scheme (among 1000 other things).

HTH!

**Comment by ces3001** [comment]
I appreciate your response. I’ve been using LinCastor on macOS for many years now. I was looking for an iOS compatible solution (that is, a cross-platform Shortcut).  I’m wondering if you might not consider adding an optional parameter to the Actions URI calls that toggles the name of the of response parameter to `text` instead of `result-data`. That would solve it, and allow for Shortcuts to directly use Actions URI. 

p.s. I would *love* to use your Actions for Obsidian solution, it’s not a money obstacle, but I can’t handle the screen “swapping” that happens on iOS... it’s too disturbing for me to use daily (some of the shortcuts I use would call AfO 4-5 times for an enormous amount of dancing on the iOS screen), so I developed my own Obsidian shortcuts library that works with the vault content directly. I’m aware of the syncing issues since I don’t automatically activate Obsidian to enforce a sync (unless I want to), and it works well for me. ... Except for this one situation that would benefit from the dataview query.

**Comment by czottmann** [comment]
> I’m wondering if you might not consider adding an optional parameter to the Actions URI calls that toggles the name of the of response parameter to text instead of result-data. That would solve it, and allow for Shortcuts to directly use Actions URI.

That'd be doable but it'd be an exception for one or two endpoints out of many. The others often return several `result-*` keys in their response – then what? My goal is a clean, consistent interface, and—in my experience—having exceptions like that which apply only to very narrow use-cases often leads down undesirable rabbit holes.

> it’s not a money obstacle, but I can’t handle the screen “swapping” that happens on iOS.

Understandable. It's annoying yet the best I could do with what's available. :|

**Comment by ces3001** [comment]
You are awesome. Appreciate your clarity around your objectives. Keep up the good work.

On Apr 10, 2024, at 9:16 AM, Carlo Zottmann ***@***.***> wrote:


I’m wondering if you might not consider adding an optional parameter to the Actions URI calls that toggles the name of the of response parameter to text instead of result-data. That would solve it, and allow for Shortcuts to directly use Actions URI.

That'd be doable but it'd be an exception for one or two endpoints out of many. The others often return several result-* keys in their response – then what? My goal is a clean, consistent interface, and—in my experience—having exceptions like that which apply only to very narrow use-cases often leads down undesirable rabbit holes.

it’s not a money obstacle, but I can’t handle the screen “swapping” that happens on iOS.

Understandable. It's annoying yet the best I could do with what's available. :|
