### ISSUE TITLE
[Feature Request] `/note/get-active` | New Return Value: Selection

### ISSUE THREAD

**Issue by FelipeRearden** [czottmann/obsidian-actions-uri#90]
Hello Carlo !!!!!

I am using the `/note/get-active` to transfer content from Obsidian to external apps on iPadOS using Shortcuts.

This way, I would like to know if you could add the text select in the Obsidian active note as one of the values returned by this route. Maybe `result-selection` ?

My idea is to add a IF statement to evaluate if the `result-selection` is empty or not and transfer the selection or the entire content of the note (`result-body`) based on this criteria.

📷 Something Like this (WIP)
![IMG_0003](https://github.com/czottmann/obsidian-actions-uri/assets/85180696/f7c9d1c9-4a87-4f64-879d-8b4694df07e1)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by czottmann** [comment]
Good idea, let me look into it!

**Comment by czottmann** [comment]
Implemented, will be rolled out in v1.6 later this week! Thanks for the idea, @FelipeRearden! 🤙🏼

**Comment by FelipeRearden** [comment]
> Implemented, will be rolled out in v1.6 later this week! Thanks for the idea, @FelipeRearden! 🤙🏼

Working perfect on version `1.6.0` on Obsidian Mobile `1.6.5`

Thank you very much Carlo for the new feature ! I am happy to know that you liked my FR

I wish you a fantastic day ☀️
