### ISSUE TITLE
Option 'below-headline' does not create a new section nor makes operation fail if section wasn't found

### ISSUE THREAD

**Issue by vitaly-rudenko** [czottmann/obsidian-actions-uri#91]
Hi! Thanks for building this amazing plugin.

Option 'below-headline' is very useful, although it seems that if no section was found with that headline, the operation still succeeds and file remains unchanged.

There are two options that I think would work well in this situation:
1. Create a new section at the bottom of the file with the given headline (may require an additional option?)
2. Fail the operation instead of calling the 'success' callback

I'd be happy to contribute if you don't have the capacity, but I first wanted to know which option sounds better (or if there's an alternative solution)

**Comment by czottmann** [comment]
@vitaly-rudenko Thanks for the report, and your offer, and I agree, this looks like a glaring oversight. I think option 1 is the better one, I'll look into it later today. Thanks for the offer, appreciate it! It's just that I work in cycles as I have more than one project, and I work on them in focussed blocks, and currently it's Action URI's time again. (I'm preparing the 1.6 release right now.)

**Comment by czottmann** [comment]
I've implemented a new optional parameter for `/note/append`/ and `/note/prepend`: `if-headline-missing=add-headline|error|skip`. If `below-headline=` is used, and the requested headline is missing, the following behavior is available:

- `if-headline-missing=add-headline` will add the headline to the end of the document before adding the append/prepend string
- `if-headline-missing=error` will return an error. That's the new default in v1.6.
- `if-headline-missing=skip` will ignore the missing headline and do nothing, which is the pre-v1.6 standard behavior.

Cool?

The changes will be live in the upcoming v1.6, later this week.

**Comment by czottmann** [comment]
Rolled out in https://github.com/czottmann/obsidian-actions-uri/releases/tag/1.6.0!
