### ISSUE TITLE
Possible to add local http server?

### ISSUE THREAD

**Issue by msageryd** [czottmann/obsidian-actions-uri#93]
This is a brilliant plugin. I'm really excited to finally be able to build the Alfred Workflow I want.

Would it be possible to present the action-uri endpoints on a local https-server, like the Omnisearch plugin can? This would make it much easier to test the api from Postman.

Screen shot from the Omnisearch plugin settings:
<img width="779" alt="image" src="https://github.com/user-attachments/assets/56453e22-fb33-48b0-9320-cc39ff4bd4f4">

**Comment by czottmann** [comment]
The `x-success`, `x-error`, or `x-cancel` parameters can be HTTP URLs, yes.

Or do you mean you're talking about the _incoming_ calls?

**Comment by msageryd** [comment]
Yes, I mean "incoming calls". The Omnisearch plugin manages tho solve the following:
1. expose urls via an http-endpoint (i.e. not obsidian://)
2. return the resulting data directly in the response

**Comment by czottmann** [comment]
I see. It's definitely in-scope for Actions URI as of right now. Sorry.
